# Generated by Django 2.2.2 on 2020-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_request_logging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='key',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
