# Generated by Django 2.2.2 on 2020-03-04 13:24

from django.db import migrations, models
import enumfields.fields

from drf_request_logging.models import RESOURCE_TYPE


class Migration(migrations.Migration):

    dependencies = [
        ('drf_request_logging', '0002_auto_20200124_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='resource',
            field=enumfields.fields.EnumField(blank=True, db_index=True, enum=RESOURCE_TYPE, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
