# Generated by Django 3.1.2 on 2020-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_request_logging', '0004_auto_20200821_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='headers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
